nginx:
  image: nginx:1.9
  restart: always
  ports:
    - "80:80"
    - "443:443"
  links:
    - confluence
    - jira
    - crowd
    - bamboo
    - crucible
    - nexus
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
confluence:
  image: ptrsoft/atlassian-confluence
  restart: always
  links:
    - database
  volumes:
    - ./atlassian-confluence/home:/opt/home
    - ./atlassian-confluence/war:/opt/war
    - ./atlassian-confluence/tomcat:/opt/tomcat
jira:
  image: ptrsoft/atlassian-jira
  restart: always
  links:
    - database
  volumes:
    - ./atlassian-jira/home:/opt/home
    - ./atlassian-jira/war:/opt/war
    - ./atlassian-jira/tomcat:/opt/tomcat
crowd:
  image: ptrsoft/atlassian-crowd
  restart: always
  links:
    - database
  volumes:
    - ./atlassian-crowd/home:/opt/home
    - ./atlassian-crowd/war:/opt/war
    - ./atlassian-crowd/tomcat:/opt/tomcat
bamboo:
  image: ptrsoft/atlassian-bamboo
  restart: always
  links:
    - database
  volumes:
    - ./atlassian-bamboo/home:/opt/home
    - ./atlassian-bamboo/war:/opt/war
    - ./atlassian-bamboo/tomcat:/opt/tomcat
crucible:
  image: ptrsoft/atlassian-crucible
  restart: always
  links:
    - database
  volumes:
    - ./atlassian-crucible/instance:/opt/instance
nexus:
  image: ptrsoft/nexus
  restart: always
  volumes:
    - ./nexus/nexus-data:/nexus-data
database:
  image: postgres:9.4
  restart: always
  volumes:
    - ./data:/var/lib/postgresql/data
    - ./atlassian-confluence/setup-confluence-db.sh:/docker-entrypoint-initdb.d/setup-confluence-db.sh
    - ./atlassian-jira/setup-jira-db.sh:/docker-entrypoint-initdb.d/setup-jira-db.sh
    - ./atlassian-crowd/setup-crowd-db.sh:/docker-entrypoint-initdb.d/setup-crowd-db.sh
    - ./atlassian-bamboo/setup-bamboo-db.sh:/docker-entrypoint-initdb.d/setup-bamboo-db.sh
    - ./atlassian-crucible/setup-crucible-db.sh:/docker-entrypoint-initdb.d/setup-crucible-db.sh
    - ./tmp:/tmp/dumps # import backups
