confluence:
  extends:
    file: confluence.yml
    service: confluence
  ports:
    - "80:8090"
  links:
    - database
  volumes:
    - home:/opt/confluence-home

database:
  image: postgres:9.4
  volumes:
    - setup-confluence-db.sh:/docker-entrypoint-initdb.d/setup-confluence-db.sh
